### PR TITLE
Add cloudformation helper scripts to the `quay.io/coreos/awscli:edge` docker image

### PR DESCRIPTION
**Pull request by mumoshu**
This is the first step to put `quay.io/coreos/awscli` docker images under control of kube-aws.

### CODE REVIEW

**Comment by mumoshu** [comment]
`quay.io/coreos/awscli:edge` is already available for `docker pull`ing!
@pieterlange @gianrubio Would you please let me know if you're ok with it?

**Comment by pieterlange** [comment]
Looks great!

**Comment by mumoshu** [comment]
Note: `groff` seems to be required by awscli to generate docs. although i thought it to be needless initially, we should keep it (thanks @pieterlange for the insight!

**Comment by mumoshu** [comment]
We're going to have a dedicated github repo for the `quay.io/coreos/awscli` docker image w/ automated builds enabled for `master` and `edge` branches and so on.
This pull request has already been recreated for the dedicated repo so keep discussing there!

https://github.com/coreos/awscli/pull/1

**Pull request closed without merging**
