### PR TITLE
version bump for dashboard and calico

### PR DESCRIPTION
**Pull request by ArchiFleKs**
Small update to latest release

### CODE REVIEW

**Comment by heschlie** [comment]
It looks like the versions are from varying releases of Calico.  The latest set of stable releases (Calico v1.6) can be found here

http://docs.projectcalico.org/v1.6/releases/

**Comment by ArchiFleKs** [comment]
@heschlie my bad, I thought tagged containers release were stable, thanks for the info

**Comment by mumoshu** [comment]
Hi @ArchiFleKs, thanks for your contribution!
I'd like to merge this once all the versions are set to stable ones 👍 
It turns out to me that I've been too lazy recently to watch every new calico release therefore I greatly appreciate this kind of contribution! :bow:

**Comment by mumoshu** [comment]
@ArchiFleKs The intent of this PR seems to be covered by https://github.com/coreos/kube-aws/pull/124 now! I'm closing this in favor it but please feel to reopen if necessary.

**Pull request closed without merging**
