### PR TITLE
Updating Calico images to Calico 2.0.2

### PR DESCRIPTION
**Pull request by heschlie**
Calico 2.0.1 was released with some bug fixes, more details here:

http://docs.projectcalico.org/v2.0/releases/

### CODE REVIEW

**Comment by mumoshu** [comment]
@heschlie Thanks as always and sorry for the delay but calico 2.0.2 seems to have already been released.
Would you mind updating this pr or send another pr for 2.0.2?

**Comment by heschlie** [comment]
@mumoshu It indeed has, and I will!

**Comment by redbaron** [comment]
@heschlie just for my education, what is relation between felix and calico node? why we use one,but not another here?

**Comment by heschlie** [comment]
@redbaron Felix is part of our backend (the biggest part I believe) that is balled up into calico-node.  I believe it can be run on its own, but calico-node includes Bird (the BGP daemon we use, though not with Flannel) as well as several other utilities to get the ball rolling, see [here](https://github.com/projectcalico/calicoctl/tree/master/calico_node) if you are interested in more details.

@mumoshu Updated to Calico 2.0.2

**Comment by mumoshu** [comment]
I've verified this by manually running E2E tests and therefore merged.

@heschlie Thanks as always!

**Pull request merged**
