### PR TITLE
Move from the old m3.medium instance type to the marginally better t2.medium

### PR DESCRIPTION
**Pull request by mumoshu**
ref #181

### CODE REVIEW

**Comment by pieterlange** [comment]
-1 Lets not use `t2` for controllers by default - you should really know what you're doing when using this instance class.

Also, 4GB of memory seems a bit on the low side when you start actually using the cluster. My not keep the `m3.medium` and suggest to use `m4.large` or `t2.large`?

**Comment by mumoshu** [comment]
@pieterlange Thanks for your feedback here!

I believe setting good defaults and moving away from the old `m3.medium` instance type is separate thing. So:

* Would you please [read my comment about that](https://github.com/coreos/kube-aws/issues/181#issuecomment-269297176)? To be more clear, It's true that I began to believe `t2.medium` is better than `m3.medium` but I'm not opposed to make `m4.large` or `t2.large` by default.

* Also, if you have any concrete advice on choosing which instance type(s) as default(s), I'd appreciate it if you could [read about my suggestions](https://github.com/coreos/kube-aws/issues/181#issuecomment-268705548) and reply with your suggestions on the instance type for etcd, controller, worker nodes 👍

**Comment by mumoshu** [comment]
Changing the subject according to what we've discussed in https://github.com/coreos/kube-aws/issues/181#issuecomment-269371054

**Comment by mumoshu** [comment]
Things seems to be left up in the air but I'm going to merge this to get the ball rolling :bow:

Let's discuss further about better default(s) in #181

**Pull request merged**
