### PR TITLE
Remove checks for dedicated spot instances

### PR DESCRIPTION
**Pull request by iameli**
[As of Jan 19, these are no longer mutually exclusive](https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-ec2-spot-instances-now-support-dedicated-tenancy/).

Will be testing this shortly and will report back here.

The two features that I added to `kube-aws`, together at last. 😃

### CODE REVIEW

**Comment by mumoshu** [comment]
@iameli Wow, that's a great news! Good catch 👍 
Did you have a chance to test this?

**Comment by mumoshu** [comment]
@iameli sorry for rushing but did you have a chance to test this? 😃

**Comment by mumoshu** [comment]
I'm merging this anyway. Thanks for contribution @iameli!

**Comment by iameli** [comment]
Finally did manage to test today! Thanks for the merge.

**Comment by mumoshu** [comment]
Thanks for testing @iameli 👍

**Pull request merged**
