### PR TITLE
Upgrade kubernetes version to v1.5.3

### PR DESCRIPTION
**Pull request by gianrubio**

### CODE REVIEW

**Comment by redbaron** [comment]
side question, why coreos images report vulnerabilities? https://quay.io/repository/coreos/hyperkube/image/9f3a4d810df5be9e7f6ce0a18545fe05a68209c88eed35c445b306c2630e4c53?tab=vulnerabilities

**Comment by gianrubio** [comment]
> side question, why coreos images report vulnerabilities? https://quay.io/repository/coreos/hyperkube/image/9f3a4d810df5be9e7f6ce0a18545fe05a68209c88eed35c445b306c2630e4c53?tab=vulnerabilities 


Good answer, all the images has the same vulnerabilities
https://quay.io/repository/coreos/hyperkube?tab=tags

BTW https://github.com/kubernetes/kubernetes/issues/25097

**Comment by redbaron** [comment]
It seems that proposed fixed doesn't work anymore

**Comment by mumoshu** [comment]
LGTM 👍 Thanks as always @gianrubio!

**Pull request merged**
